### ISSUE TITLE
 when install plugin

### ISSUE THREAD

**Issue by kam7awy** [vidinoti/cordova-plugin-PixLive#10]
when install plugin show this line ::  You need to have a valid PixLive SDK license to use this plugin. Check http://www.pixlive.info for more information.  
However, do everything right and VR not working

sudo cordova plugin add cordova-plugin-pixlive@latest --variable LICENSE_KEY="key" --variable PIXLIVE_SDK_IOS_LOCATION=\"/path/VDRSDK-IOS-6.5.12/VDARSDK.framework\" --variable PIXLIVE_SDK_ANDROID_LOCATION=\"/path/VDARSDK-Android-6.5.17/libs/vdarsdk-release.aar\"
Installing "cordova-plugin-pixlive" for android
Copying PixLive SDK for iOS...
Copying PixLive SDK for Android...
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app

    You need to have a valid PixLive SDK license to use this plugin. Check http://www.pixlive.info for more information.
    
Installing "cordova-plugin-pixlive" for ios

    You need to have a valid PixLive SDK license to use this plugin. Check http://www.pixlive.info for more information.
    
Adding translations in iOS project for Beacons...
Changing app name in platforms/ios/Sehetak Beldonya/Sehetak Beldonya-Info.plist
path infoPlist.strings platforms/ios/projectname/en.lproj/InfoPlist.strings
path infoPlist.strings platforms/ios/projectname/fr.lproj/InfoPlist.strings
path infoPlist.strings platforms/ios/projectname/de.lproj/InfoPlist.strings
path infoPlist.strings platforms/ios/projectname/nl.lproj/InfoPlist.strings
path infoPlist.strings platforms/ios/projectname/Base.lproj/InfoPlist.strings
Adding cordova-plugin-pixlive to package.json
Adding files to Xcode project...
[platforms/ios/Sehetak Beldonya.xcodeproj/project.pbxproj] now has translations for languages: en,fr,de,nl,Base

**Comment by JL-Vidinoti** [comment]
Hello,
You need a valid V-Director license. The message that appears is just a warning/information. You can get your license directly in V-Director (https://armanager.vidinoti.com)
You can find additional information about how to create an app there: https://vidinoti.github.io/documentation/sdk/create-an-app
If you want more help, please describe specifically the problem you have.
