### ISSUE TITLE
Cordova 10.0.0/Android build isssue

### ISSUE THREAD

**Issue by infuzz** [vidinoti/cordova-plugin-PixLive#11]
I have an issue with your plugin for android cordova. When added, your plugin prevents the build to create the apk as expected. What was strange is that there is absolutely no error.
So I have opened an issue on cordova github, they have a look and find what is going wrong with the plugin.
You can see the issue, all version used and solution [Here](https://github.com/apache/cordova/issues/258) 

Could you please review issue ?

**Comment by JL-Vidinoti** [comment]
Please see comment of breautek: https://github.com/apache/cordova/issues/258#issuecomment-726994677
What he describes is correct. We generate multiple APKs for reducing the size of the final APK.
