### ISSUE TITLE
Problem with click on button 

### ISSUE THREAD

**Issue by webquali** [vidinoti/cordova-plugin-PixLive#4]
Hi,

I have this layout, my problem I can't click to button "Home"

`<ion-view style="background-color: transparent !important;" hide-nav-bar="true">
    <pxl-view pxl-context-enter="contextEnter" >
        <button ng-click="closeArViewButton()" class="button button-balanced text-center">HOME</button>
    </pxl-view>
</ion-view>`

Can you help me understand why?

**Comment by jleuleu** [comment]
Hello,
The camera view intercepts the click events. This is necessary to interact with AR contents.
You need to disable the interception by calling `arView.disableTouch()`.

Below is an example that enable/disable the touch event when AR content is displayed.
```
//enable PixLive SDK to catch the touch event when a content is displayed
addListener("presentAnnotations",function(event){
    arView.enableTouch();
});
//disable PixLive SDK to catch the touch event when a content is hidden
addListener("hideAnnotations",function(event){
    arView.disableTouch();
});
```

Johan
