### ISSUE TITLE
IOS error : Synchronize error server returned status code 400

### ISSUE THREAD

**Issue by slimt623** [vidinoti/cordova-plugin-PixLive#6]
IOS error : Synchronize error server returned status code 400

**Comment by JL-Vidinoti** [comment]
Please give more information if you want some help. What is the complete error message?
Did you follow the README guide? In particular, have you registered your app in [V-Director](https://armanager.vidinoti.com)?

**Comment by slimt623** [comment]
I tried to build an iOS app on cordova using your sdk , however when I open the app on my phone I get this error
![whatsapp image 2018-07-09 at 07 53 48](https://user-images.githubusercontent.com/17980517/42449097-5bfba4f8-834d-11e8-81da-736024654096.jpeg)

**Comment by JL-Vidinoti** [comment]
Can you please attach the application logs.
